<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>utils.hpp</title>
</head>
<body>
<article id="standardese-utils.hpp" class="standardese-file-documentation">
<h1 class="standardese-file-documentation-heading">Header file <code>utils.hpp</code></h1>
<pre><code class="standardese-language-cpp standardese-entity-synopsis"><span class="pre">#include</span> <span class="pre">&quot;</span><span class="typ dec var fun">config.hpp</span><span class="pre">&quot;</span>

<span class="pre">#include</span> <span class="pre">&lt;</span><span class="typ dec var fun">exception</span><span class="pre">&gt;</span>

<span class="pre">#include</span> <span class="pre">&lt;</span><span class="typ dec var fun">system_error</span><span class="pre">&gt;</span>

<span class="pre">#define</span> <span class="typ dec var fun">BOOST_OUTCOME_ERROR_FROM_EXCEPTION_HPP</span>

<span class="kwd">namespace</span> <span class="typ dec var fun">outcome_v2_xxx</span>
<span class="pun">{</span>
    <span class="typ dec var fun">std::error_code</span> <a href="doc_utils.html#standardese-outcome_v2_xxx::error_from_exception(std::exception_ptr&amp;&amp;,std::error_code)"><span class="typ dec var fun">error_from_exception</span></a><span class="pun">(</span><span class="typ dec var fun">std::exception_ptr</span><span class="pun">&amp;&amp;</span> <a href="doc_utils.html#standardese-outcome_v2_xxx::error_from_exception(std::exception_ptr&amp;&amp;,std::error_code).ep"><span class="typ dec var fun">ep</span></a> <span class="pun">=</span> <span class="kwd">std</span><span class="pun">::</span><span class="kwd">current_exception</span><span class="pun">(</span><span class="pun">,</span> <span class="typ dec var fun">std::error_code</span> <a href="doc_utils.html#standardese-outcome_v2_xxx::error_from_exception(std::exception_ptr&amp;&amp;,std::error_code).not_matched"><span class="typ dec var fun">not_matched</span></a> <span class="pun">=</span> <span class="kwd">std</span><span class="pun">::</span><span class="kwd">make_error_code</span><span class="pun">(</span><span class="kwd">std</span><span class="pun">::</span><span class="kwd">errc</span><span class="pun">::</span><span class="kwd">resource_unavailable_try_again</span><span class="pun">)</span> <span class="kwd">noexcept</span><span class="pun">;</span>

    <span class="kwd">void</span> <a href="doc_utils.html#standardese-outcome_v2_xxx::try_throw_std_exception_from_error(std::error_code,std::stringconst&amp;)"><span class="typ dec var fun">try_throw_std_exception_from_error</span></a><span class="pun">(</span><span class="typ dec var fun">std::error_code</span> <a href="doc_utils.html#standardese-outcome_v2_xxx::try_throw_std_exception_from_error(std::error_code,std::stringconst&amp;).ec"><span class="typ dec var fun">ec</span></a><span class="pun">,</span> <span class="typ dec var fun">std::string</span> <span class="kwd">const</span><span class="pun">&amp;</span> <a href="doc_utils.html#standardese-outcome_v2_xxx::try_throw_std_exception_from_error(std::error_code,std::stringconst&amp;).msg"><span class="typ dec var fun">msg</span></a> <span class="pun">=</span> <span class="kwd">std</span><span class="pun">::</span><span class="kwd">string</span><span class="pun">{</span><span class="pun">)</span><span class="pun">;</span>
<span class="pun">}</span>
</code></pre>
<section id="standardese-outcome_v2_xxx" class="standardese-entity-documentation">
<section id="standardese-outcome_v2_xxx::error_from_exception(std::exception_ptr&amp;&amp;,std::error_code)" class="standardese-entity-documentation">
<h3 class="standardese-entity-documentation-heading">Function <code>error_from_exception</code></h3>
<pre><code class="standardese-language-cpp standardese-entity-synopsis"><span class="typ dec var fun">std::error_code</span> <span class="typ dec var fun">error_from_exception</span><span class="pun">(</span><span class="typ dec var fun">std::exception_ptr</span><span class="pun">&amp;&amp;</span> <a href="doc_utils.html#standardese-outcome_v2_xxx::error_from_exception(std::exception_ptr&amp;&amp;,std::error_code).ep"><span class="typ dec var fun">ep</span></a> <span class="pun">=</span> <span class="kwd">std</span><span class="pun">::</span><span class="kwd">current_exception</span><span class="pun">(</span><span class="pun">,</span> <span class="typ dec var fun">std::error_code</span> <a href="doc_utils.html#standardese-outcome_v2_xxx::error_from_exception(std::exception_ptr&amp;&amp;,std::error_code).not_matched"><span class="typ dec var fun">not_matched</span></a> <span class="pun">=</span> <span class="kwd">std</span><span class="pun">::</span><span class="kwd">make_error_code</span><span class="pun">(</span><span class="kwd">std</span><span class="pun">::</span><span class="kwd">errc</span><span class="pun">::</span><span class="kwd">resource_unavailable_try_again</span><span class="pun">)</span> <span class="kwd">noexcept</span><span class="pun">;</span>
</code></pre>
<p id="standardese-outcome_v2_xxx::error_from_exception(std::exception_ptr&amp;&amp;,std::error_code)-brief" class="standardese-brief-section">Utility function which tries to match the exception in the pointer provided
to an equivalent error code. Ought to work for all standard STL types.</p>
<dl id="standardese-outcome_v2_xxx::error_from_exception(std::exception_ptr&amp;&amp;,std::error_code)-inline-sections" class="standardese-inline-sections">
<dt>Effects:</dt>
<dd>Rethrows the exception in the pointer, and via a long sequence of <code>catch</code>
clauses attempts to match the equivalent error code. If a match is found, the
pointer is reset to null. If a match is not found, <em>not_matched</em> is returned instead
and the pointer is left unmodified.</dd>
</dl>
<h4 class="standardese-list-section-heading">Parameters</h4>
<ul id="standardese-outcome_v2_xxx::error_from_exception(std::exception_ptr&amp;&amp;,std::error_code)-params" class="standardese-list-section">
<li id="standardese-outcome_v2_xxx::error_from_exception(std::exception_ptr&amp;&amp;,std::error_code).ep">
<dl id="standardese-outcome_v2_xxx::error_from_exception(std::exception_ptr&amp;&amp;,std::error_code).ep" class="standardese-term-description-item">
<dt><code>ep</code></dt>
<dd>&mdash; The pointer to an exception to convert. If matched, on exit this is
reset to a null pointer.</dd>
</dl>
</li>
</ul>
<section id="standardese-outcome_v2_xxx::error_from_exception(std::exception_ptr&amp;&amp;,std::error_code).not_matched" class="standardese-entity-documentation">
<h3 class="standardese-entity-documentation-heading">Parameter <code>not_matched</code></h3>
<pre><code class="standardese-language-cpp standardese-entity-synopsis"><span class="typ dec var fun">std::error_code</span> <span class="typ dec var fun">not_matched</span> <span class="pun">=</span> <span class="kwd">std</span><span class="pun">::</span><span class="kwd">make_error_code</span><span class="pun">(</span><span class="kwd">std</span><span class="pun">::</span><span class="kwd">errc</span><span class="pun">::</span><span class="kwd">resource_unavailable_try_again</span></code></pre>
<p id="standardese-outcome_v2_xxx::error_from_exception(std::exception_ptr&amp;&amp;,std::error_code).not_matched-brief" class="standardese-brief-section">The error code to return if we could not match the exception.</p>
<p>Note that a null pointer in returns a null error code.</p>
</section>
<hr class="standardese-entity-documentation-break" />
</section>
<hr class="standardese-entity-documentation-break" />
<section id="standardese-outcome_v2_xxx::try_throw_std_exception_from_error(std::error_code,std::stringconst&amp;)" class="standardese-entity-documentation">
<h3 class="standardese-entity-documentation-heading">Function <code>try_throw_std_exception_from_error</code></h3>
<pre><code class="standardese-language-cpp standardese-entity-synopsis"><span class="kwd">void</span> <span class="typ dec var fun">try_throw_std_exception_from_error</span><span class="pun">(</span><span class="typ dec var fun">std::error_code</span> <a href="doc_utils.html#standardese-outcome_v2_xxx::try_throw_std_exception_from_error(std::error_code,std::stringconst&amp;).ec"><span class="typ dec var fun">ec</span></a><span class="pun">,</span> <span class="typ dec var fun">std::string</span> <span class="kwd">const</span><span class="pun">&amp;</span> <a href="doc_utils.html#standardese-outcome_v2_xxx::try_throw_std_exception_from_error(std::error_code,std::stringconst&amp;).msg"><span class="typ dec var fun">msg</span></a> <span class="pun">=</span> <span class="kwd">std</span><span class="pun">::</span><span class="kwd">string</span><span class="pun">{</span><span class="pun">)</span><span class="pun">;</span>
</code></pre>
<p id="standardese-outcome_v2_xxx::try_throw_std_exception_from_error(std::error_code,std::stringconst&amp;)-brief" class="standardese-brief-section">Utility function which tries to throw the equivalent STL exception type for
some given error code, not including <code>system_error</code>.</p>
<dl id="standardese-outcome_v2_xxx::try_throw_std_exception_from_error(std::error_code,std::stringconst&amp;)-inline-sections" class="standardese-inline-sections">
<dt>Effects:</dt>
<dd>If the input error code has a category of <code>generic_category()</code> (all platforms)
or <code>system_category()</code> (POSIX only), throw the STL exception type matching
the <code>errno</code> domained code if one is available. For example, <code>ENOMEM</code> would cause
<code>std::bad_alloc()</code> to be thrown.</dd>
</dl>
<h4 class="standardese-list-section-heading">Parameters</h4>
<ul id="standardese-outcome_v2_xxx::try_throw_std_exception_from_error(std::error_code,std::stringconst&amp;)-params" class="standardese-list-section">
<li id="standardese-outcome_v2_xxx::try_throw_std_exception_from_error(std::error_code,std::stringconst&amp;).ec">
<dl id="standardese-outcome_v2_xxx::try_throw_std_exception_from_error(std::error_code,std::stringconst&amp;).ec" class="standardese-term-description-item">
<dt><code>ec</code></dt>
<dd>&mdash; The error code to try to convert into a STL exception throw.</dd>
</dl>
</li>
<li id="standardese-outcome_v2_xxx::try_throw_std_exception_from_error(std::error_code,std::stringconst&amp;).msg">
<dl id="standardese-outcome_v2_xxx::try_throw_std_exception_from_error(std::error_code,std::stringconst&amp;).msg" class="standardese-term-description-item">
<dt><code>msg</code></dt>
<dd>&mdash; Optional custom message for the STL exception type.</dd>
</dl>
</li>
</ul>
</section>
<hr class="standardese-entity-documentation-break" />
</section>
</article>
</body>
</html>
